services:
  - type: web
    name: esit-tech-support
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/api/app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false  # Set this manually in Render dashboard
      - key: FEEDBACK_DIR
        value: /opt/render/project/src/data
